# Copy this file to "client_config.yaml" with the correct information.
# Go to https://discord.com/developers and lookup your bot's details.
# The token is located in the "Bot" section

client_token: "<TOKEN GOES HERE>"
